version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
      - ./logs:/app/logs
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=xseller8
      - DB_USER=postgres
      - DB_PASSWORD=your_secure_password
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=xseller8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
